"""
Image Handler
Locates, processes, and encodes product images.
"""
import os
import base64
import glob
from typing import Optional, Dict, Any
from io import BytesIO

try:
    from PIL import Image
    from .fal_enhancer import FalEnhancer
except ImportError:
    Image = None


class ImageHandler:
    """
    Handles image discovery and processing for products.
    """
    
    def __init__(self, project_path: str):
        self.images_dir = os.path.join(project_path, "data", "assets", "product_images")
        self.generics_dir = os.path.join(self.images_dir, "generics")
        self.processed_dir = os.path.join(self.images_dir, "processed")
        self.fal_enhancer = FalEnhancer()
        
        # Ensure directories
        os.makedirs(self.processed_dir, exist_ok=True)
        
        # Cache for fuzzy matching
        self.file_cache = []
        self._build_file_cache()

    def _build_file_cache(self):
        """Pre-load all image filenames for fuzzy searching"""
        try:
            files = [f for f in os.listdir(self.images_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
            for f in files:
                # Store tuple: (original_filename, normalized_name)
                # Normalize: Remove 0.00, extension, brands
                name = os.path.splitext(f)[0].upper()
                norm = name.replace("0.00", "").replace("_", "").replace("-", "").replace(" ", "")
                # Remove common brands to clean up
                for brand in ["SKF", "FAG", "TIMKEN", "NTN", "KOYO", "NSK", "INA", "MRC", "NACHI", "CR", "NATIONAL"]:
                    norm = norm.replace(brand, "")
                
                self.file_cache.append({'filename': f, 'normalized': norm, 'path': os.path.join(self.images_dir, f)})
            print(f"   📂 Cached {len(self.file_cache)} files for fuzzy matching")
        except Exception as e:
            print(f"Error building file cache: {e}")
        
    def get_image_for_product(self, product_code: str, record: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        Find, Enhance, and Encode image.
        Returns dict with 'image_1920', 'image_status', 'image_path'.
        """
        if not Image:
             return {'image_1920': False, 'image_status': 'missing_dependency'}
             
        # Normalize code for search
        safe_code = product_code.replace("/", "_").strip()
        
        # 1. Search Logic
        # Try multiple variations including Brand Prefix/Suffix
        search_candidates = [safe_code]
        if record and record.get('brand'):
            brand = record['brand'].replace(" ", "_").upper()
            search_candidates.append(f"{brand}_{safe_code}")
            search_candidates.append(f"{safe_code}_{brand}")
            
        image_path = None
        # print(f"DEBUG: Searching for images for {safe_code}. Candidates: {search_candidates}")
        for candidate in search_candidates:
            found = self._find_image(candidate)
            if found:
                # print(f"DEBUG: Found match: {found}")
                image_path = found
                break
        
        # 1.2 Fuzzy Fallback
        if not image_path:
            # Try to match code against cached file list
            # Normalize target code
            norm_code = safe_code.upper().replace("/", "").replace("-", "").replace(" ", "").replace("_", "")
            
            # Require minimum length to avoid bad matches (e.g. 'C3')
            if len(norm_code) > 3: 
                for entry in self.file_cache:
                    # Check if code is inside filename
                    if norm_code in entry['normalized']:
                        print(f"   🔍 Fuzzy Match: {norm_code} -> {entry['filename']}")
                        image_path = entry['path']
                        break
        
        is_generic = False
        
        # 1.5 Generic Fallback Logic
        if not image_path and record:
            # Map category to generic filename
            # Simple heuristic mapping based on content generated by Analyzer
            # Improved Heuristic Mapping
            # Combine all text fields for search
            text_corpus = (
                str(record.get('type', '')) + " " + 
                str(record.get('marketing_description', '')) + " " + 
                str(record.get('marketing_title', '')) + " " +
                str(record.get('original_code', ''))
            ).lower()
            
            generic_filename = None
            
            # Priority Mapping
            if 'spherical' in text_corpus or '222' in text_corpus or '223' in text_corpus:
                generic_filename = "spherical_roller_swiss.jpg"
            elif 'taper' in text_corpus or '320' in text_corpus or '302' in text_corpus:
                generic_filename = "tapered_roller_swiss.jpg"
            elif 'deep groove' in text_corpus or '600' in text_corpus or '620' in text_corpus or '630' in text_corpus:
                generic_filename = "deep_groove_swiss.jpg"
            elif 'cylindrical' in text_corpus or 'nu' in text_corpus or 'nj' in text_corpus:
                generic_filename = "cylindrical_roller_swiss.jpg"
            elif 'needle' in text_corpus or 'rnas' in text_corpus:
                generic_filename = "needle_roller_swiss.jpg"
            elif 'seal' in text_corpus or 'oil' in text_corpus:
                 generic_filename = "oil_seal_swiss.jpg"
            
            # Ultimate Fallback (if still nothing, assume Deep Groove or Spherical based on project context)
            if not generic_filename:
                 # Default to deep groove as a safe "looks like a bearing" image
                 generic_filename = "deep_groove_swiss.jpg"
                 
            if generic_filename:
                # Check if we have the master generic
                # Note: Generics generated by FalEnhancer are already 'processed' (trimmed/resized/swiss)
                # But my script saved them as .jpg. Let's check the filename convention from the script.
                # The script passed 'spherical_roller.jpg' to generate_from_text, which calls _process_result
                # _process_result saves as f"{name}_swiss.jpg".
                # So 'spherical_roller.jpg' -> 'spherical_roller_swiss.jpg'.
                
                # Wait, generate_generics.py calls run_command with simple filenames.
                # Let's verify what the script produces.
                # Script: generate_from_text(desc, "spherical_roller.jpg")
                # Enhancer._process_result: saves as "spherical_roller_swiss.jpg" inside dirname/processed?
                # Ah, generate_from_text constructs dummy path: .../generics/spherical_roller.jpg
                # So output is .../generics/processed/spherical_roller_swiss.jpg
                
                # Let's fix the path logic here to match whatever structure is created.
                # Ideally, I should check the output of the generation script first.
                # But assuming standard behavior:
                gen_path = os.path.join(self.generics_dir, "processed", generic_filename) 
                
                if os.path.exists(gen_path):
                    image_path = gen_path
                    is_generic = True
        
        # 2. Enhancement Logic
        if image_path:
            try:
                # Check for cached enhanced version
                filename = os.path.basename(image_path)
                name, ext = os.path.splitext(filename)
                enhanced_path = os.path.join(self.processed_dir, f"{name}_swiss.jpg")
                
                final_path = image_path # Default to raw
                
                if is_generic:
                    # Generic is already processed (Swiss style)
                    final_path = image_path
                    status = 'generic_fallback'
                elif os.path.exists(enhanced_path):
                     # Cache Hit
                     final_path = enhanced_path
                     status = 'enhanced_cached'
                elif record:
                     # New Enhancement
                     print(f"   ✨ Enhancing: {filename}...")
                     new_path = self.fal_enhancer.enhance_image(image_path, record)
                     if new_path:
                         final_path = new_path
                         status = 'enhanced_new'
                     else:
                         status = 'raw_fallback'
                else:
                    status = 'raw'

                # Encode
                return {
                    'image_1920': self._process_image(final_path),
                    'image_status': status,
                    'image_path': final_path
                }
            except Exception as e:
                print(f"Error enhancing image: {e}")
                
        return {'image_1920': False, 'image_status': 'missing'}
        
    def _find_image(self, name_stem: str) -> Optional[str]:
        """Find image file with any extension"""
        # Search for common extensions
        patterns = [
            os.path.join(self.images_dir, f"{name_stem}.jpg"),
            os.path.join(self.images_dir, f"{name_stem}.png"),
            os.path.join(self.images_dir, f"{name_stem}.jpeg")
        ]
        
        for p in patterns:
            # Case insensitive check could be added here if needed
            if os.path.exists(p):
                return p
                
        # Glob for case insensitivity if needed (expensive, skip for now)
        return None

    def _process_image(self, image_path: str) -> str:
        """Resize and convert to base64"""
        try:
            with Image.open(image_path) as img:
                # Odoo optimization: Resize to max 1024x1024
                img.thumbnail((1024, 1024))
                
                # Convert to RGB if needed (handle PNG transparency)
                if img.mode in ('RGBA', 'P'):
                    img = img.convert('RGB')
                
                buffer = BytesIO()
                img.save(buffer, format="JPEG", quality=85)
                return base64.b64encode(buffer.getvalue()).decode('utf-8')
        except Exception as e:
            print(f"Error processing image {image_path}: {e}")
            return None
